# Używamy oficjalnego obrazu Ubuntu jako bazowego
FROM ubuntu:latest

# Instalujemy curl
RUN apt-get update && apt-get install -y curl

# Ustawiamy domyślną komendę po uruchomieniu kontenera
CMD ["bash"]
