version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    networks:
      - my_network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: db-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - my_network
    ports:
      - "5432:5432"
    restart: always

networks:
  my_network:
    driver: bridge
